from pathlib import Path


def test_main_stdout_saved(student_output_dir):
    output_dir = Path(student_output_dir)
    stdout_files = sorted(output_dir.glob("*.stdout"))

    print(f"Saved stdout files: {[f.name for f in stdout_files]}")
    assert stdout_files, "No stdout files were generated by main.cpp"

    for stdout_file in stdout_files:
        content = stdout_file.read_text().strip()
        print(f"{stdout_file.name} bytes={len(content)}")
        assert content, f"{stdout_file.name} is empty"

